services:
  react-prod:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-reactjs-sample
    ports:
      - "8080:8080"

  react-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev # Garante que ele vai parar no estágio 'dev' do seu Dockerfile
    ports:
      - "5173:5173"
    environment:
      - WATCHPACK_POLLING=true # Ajuda o Vite a detectar mudanças em alguns sistemas operacionais
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/ # Não sincronize a pasta local com a do container
